export { default as Button } from './button.component';
export { default as Header } from './header.component';
export { default as Categories } from './categories.component';
export { default as SortPopup } from './sort-popup.component';
export { default as PizzaBlock } from './pizza-block.component';
export { default as PizzaLoadingBlock } from './loading-block.component';
export { default as CartItem } from './сart-item.component';
export { default as CartEmpty } from './cart-empty.component';
export { default as FormOrderPopup } from './from-order-popup.component';
