# This workflow will do a clean install of node dependencies,
# build the source code and run tests across different versions of node
#
# for "npm ci" see https://docs.npmjs.com/cli/ci.html
#

name: npm-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: CI=false npm run build --if-present
    - run: npm test
